import {normalizeDatabase,filterQuestions,shuffled,unique} from './quiz.js?v=2.0.1';
import {getSessions,getSet,toggleSet,saveSession,clearStats,summary} from './stats.js?v=2.0.1';
const app=document.querySelector('#app');
const state={all:[],filtered:[],favorites:getSet('favorites'),review:getSet('review'),filters:{ano:'',categoria:'',busca:'',favoritos:false,revisao:false},session:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=s=>esc(s).split('\n').map(line=>/^(Fonte:|Disponível em:|Acesso em:|Adaptado de:)|\b(ed\.|org\.|v\.|n\.|p\.)\b|\([Aa]daptado\)\.?$|^[A-ZÁÉÍÓÚÂÊÔÃÕÇ][A-ZÁÉÍÓÚÂÊÔÃÕÇ .;,&-]{2,},\s*[A-Z]/.test(line.trim())?`<span class="bibliographic-ref">${line}</span>`:line).join('<br>');
const asset=p=>p?`./${p.replace(/^\.\//,'')}`:'';
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('enade.theme',theme);document.querySelector('#themeToggle').textContent=theme==='dark'?'☀':'☾';}
setTheme(localStorage.getItem('enade.theme')|| (matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));
document.querySelector('#themeToggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>b.dataset.view==='estatisticas'?renderStats():renderHome());
function select(label,id,values,value=''){return `<label>${label}<select id="${id}"><option value="">Todos</option>${values.map(v=>`<option ${String(v)===String(value)?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
function renderHome(){
  state.session=null; state.filtered=filterQuestions(state.all,{...state.filters,favoritos:state.filters.favoritos?state.favorites:null,revisao:state.filters.revisao?state.review:null});
  app.innerHTML=`<section class="hero"><div><span class="eyebrow">Plataforma de estudos</span><h1>Prepare-se com foco.<br><em>Evolua com evidências.</em></h1><p>Questões do ENADE de História organizadas para prática, revisão e acompanhamento do seu desempenho.</p></div><div class="hero-score"><strong>${state.all.length}</strong><span>questões no banco</span><small>${unique(state.all,'year').join(' · ')}</small></div></section>
  <section class="panel"><div class="section-title"><div><span class="eyebrow">Personalize sua seção</span></div><span class="result-count"><strong>${state.filtered.length}</strong> encontradas</span></div>
  <div class="filters"><label class="search">Buscar<input id="busca" value="${esc(state.filters.busca)}" placeholder="Palavra-chave ou conteúdo"></label>${select('Ano','ano',unique(state.all,'year'),state.filters.ano)}${select('Categoria','categoria',unique(state.all,'categoria'),state.filters.categoria)}</div>
  <div class="quick-filters"><label><input id="onlyFav" type="checkbox" ${state.filters.favoritos?'checked':''}> ★ Favoritas (${state.favorites.size})</label><label><input id="onlyReview" type="checkbox" ${state.filters.revisao?'checked':''}> ↻ Revisar depois (${state.review.size})</label></div>
  <div class="start-row"><label>Quantidade<select id="amount">${[10,20,30,50,state.filtered.length].filter((x,i,a)=>x&&x<=state.filtered.length&&a.indexOf(x)===i).map(x=>`<option>${x}</option>`).join('')}</select></label><button id="start" class="primary" ${state.filtered.length?'':'disabled'}>Começar sessão →</button></div></section>`;
  ['ano','categoria'].forEach(id=>document.querySelector('#'+id).onchange=e=>{state.filters[id]=e.target.value;renderHome()});
  let timer;document.querySelector('#busca').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>{state.filters.busca=e.target.value;renderHome()},250)};
  document.querySelector('#onlyFav').onchange=e=>{state.filters.favoritos=e.target.checked;renderHome()};document.querySelector('#onlyReview').onchange=e=>{state.filters.revisao=e.target.checked;renderHome()};
  document.querySelector('#start').onclick=()=>startSession(Number(document.querySelector('#amount').value));
}
function startSession(amount){const items=shuffled(state.filtered).slice(0,amount);state.session={items,index:0,answers:{},started:Date.now(),revealed:false};renderQuestion();}
function renderQuestion(){const s=state.session,q=s.items[s.index],picked=s.answers[q.id];const answered=picked!==undefined, progress=Math.round((s.index/s.items.length)*100);app.innerHTML=`<section class="quiz-shell"><div class="quiz-top"><button class="text-button" id="quit">← Encerrar</button><div class="progress-wrap"><div><span>Questão ${s.index+1} de ${s.items.length}</span><span>${progress}%</span></div><div class="progress"><i style="width:${progress}%"></i></div></div><div class="question-actions"><button id="fav" title="Favoritar" class="icon-button ${state.favorites.has(q.id)?'on':''}">★</button><button id="review" title="Revisar depois" class="icon-button ${state.review.has(q.id)?'on':''}">↻</button></div></div>
  <article class="question-card"><div class="tags"><span>${esc(q.year)}</span><span>${esc(q.categoria)}</span></div><p class="origin">${esc(q.origem||q.area)}</p><h1>${lines(q.enunciado)}</h1>${q.imagem?`<figure><img src="${asset(q.imagem)}" alt="Imagem de apoio da questão"><figcaption>${esc(q.imagemCredito||'')}</figcaption></figure>`:''}<fieldset><legend>Escolha uma alternativa</legend>${q.alternativas.map((a,i)=>`<label class="answer ${picked===i?'selected':''}"><input type="radio" name="answer" value="${i}" ${picked===i?'checked':''} ${s.revealed?'disabled':''}><b>${String.fromCharCode(65+i)}</b><span>${lines(a)}</span></label>`).join('')}</fieldset></article><div class="quiz-nav"><button id="prev" ${s.index===0?'disabled':''}>Anterior</button><button id="next" class="primary" ${!answered?'disabled':''}>${s.index===s.items.length-1?'Ver resultado':'Próxima'} →</button></div></section>`;
  if(answered){document.querySelectorAll('.answer').forEach((label,i)=>{if(i===q.correta)label.classList.add('correct');else if(i===picked)label.classList.add('wrong')});document.querySelectorAll('input[name=answer]').forEach(r=>r.disabled=true)}
  document.querySelectorAll('input[name=answer]').forEach(r=>r.onchange=e=>{s.answers[q.id]=Number(e.target.value);s.revealed=true;renderQuestion()});document.querySelector('#fav').onclick=()=>{state.favorites=toggleSet('favorites',q.id);renderQuestion()};document.querySelector('#review').onclick=()=>{state.review=toggleSet('review',q.id);renderQuestion()};document.querySelector('#quit').onclick=()=>confirm('Encerrar esta sessão?')&&finish();document.querySelector('#prev').onclick=()=>{s.index--;s.revealed=s.answers[s.items[s.index].id]!==undefined;renderQuestion()};document.querySelector('#next').onclick=()=>{if(s.index===s.items.length-1)finish();else{s.index++;s.revealed=s.answers[s.items[s.index].id]!==undefined;renderQuestion()}};
}
function finish(){const s=state.session,answered=s.items.filter(q=>s.answers[q.id]!==undefined),correct=answered.filter(q=>s.answers[q.id]===q.correta);const byCategory={};answered.forEach(q=>{byCategory[q.categoria]??={acertos:0,total:0};byCategory[q.categoria].total++;if(s.answers[q.id]===q.correta)byCategory[q.categoria].acertos++});const record={id:Date.now(),data:new Date().toISOString(),modo:'simulado',respondidas:answered.length,acertos:correct.length,duracao:Math.round((Date.now()-s.started)/1000),porCategoria:byCategory};if(answered.length)saveSession(record);app.innerHTML=`<section class="result panel"><span class="eyebrow">Sessão concluída</span><div class="score-ring" style="--score:${answered.length?correct.length/answered.length*360:0}deg"><strong>${answered.length?Math.round(correct.length/answered.length*100):0}%</strong></div><h1>${correct.length} acertos em ${answered.length} respostas</h1><p>Tempo de estudo: ${Math.floor(record.duracao/60)}min ${record.duracao%60}s</p><div class="result-actions"><button id="home">Nova sessão</button><button id="stats" class="primary">Ver estatísticas →</button></div></section>`;document.querySelector('#home').onclick=renderHome;document.querySelector('#stats').onclick=renderStats;}
function renderStats(){const sessions=getSessions(),sum=summary(sessions);app.innerHTML=`<section class="stats"><div class="section-title"><div><span class="eyebrow">Seu desempenho</span><h1>Estatísticas locais</h1></div><button id="clear" class="danger" ${sessions.length?'':'disabled'}>Limpar histórico</button></div><div class="metrics"><div><span>Sessões</span><strong>${sum.sessions}</strong></div><div><span>Questões respondidas</span><strong>${sum.answered}</strong></div><div><span>Taxa de acerto</span><strong>${sum.rate}%</strong></div><div><span>Favoritas · revisão</span><strong>${state.favorites.size} · ${state.review.size}</strong></div></div><section class="panel"><h2>Desempenho por categoria</h2>${Object.keys(sum.byCategory).length?`<div class="theme-bars">${Object.entries(sum.byCategory).sort((a,b)=>b[1].total-a[1].total).map(([k,v])=>{const p=Math.round(v.acertos/v.total*100);return `<div><p><span>${esc(k)}</span><b>${p}% · ${v.total} respostas</b></p><div class="progress"><i style="width:${p}%"></i></div></div>`}).join('')}</div>`:'<div class="empty"><strong>Ainda não há resultados.</strong><p>Conclua uma sessão para acompanhar sua evolução.</p><button id="goHome" class="primary">Começar agora</button></div>'}</section><section class="panel"><h2>Histórico recente</h2>${sessions.length?`<div class="history">${sessions.slice(0,10).map(s=>`<div><span>${new Date(s.data).toLocaleDateString('pt-BR')}</span><b>${s.acertos}/${s.respondidas} acertos</b><small>${esc(s.modo)} · ${Math.floor(s.duracao/60)}min</small></div>`).join('')}</div>`:'<p class="muted">Nenhuma sessão registrada.</p>'}</section></section>`;document.querySelector('#goHome')?.addEventListener('click',renderHome);document.querySelector('#clear').onclick=()=>{if(confirm('Apagar todo o histórico de sessões?')){clearStats();renderStats()}};}
try{const response=await fetch('./questoes.json?v=2.0.2');if(!response.ok)throw new Error('Falha ao carregar o banco');state.all=normalizeDatabase(await response.json());renderHome()}catch(err){app.innerHTML=`<section class="panel error-screen"><h1>Não foi possível abrir o banco de questões</h1><p>${esc(err.message)}. Inicie um servidor local conforme o README; navegadores bloqueiam JSON ao abrir o arquivo diretamente.</p></section>`;}
